version: '3.0'

services:
  grafana:
    container_name: 'grafana-llm-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.1.0}
    environment:
      GF_FEATURE_TOGGLES_ENABLE: 'externalServiceAuth'
      OPENAI_API_KEY: $OPENAI_API_KEY
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-llm-app
      - ./provisioning:/etc/grafana/provisioning
