version: '3.0'

services:
  grafana:
    container_name: 'grafana-llm-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.1.0}
    environment:
      AZURE_OPENAI_API_KEY: $AZURE_OPENAI_API_KEY
      GF_LOG_LEVEL: debug
      OPENAI_ORGANIZATION_ID: $OPENAI_ORGANIZATION_ID
      OPENAI_API_KEY: $OPENAI_API_KEY
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-llm-app
      - ./provisioning:/etc/grafana/provisioning
      - ./llmexamples-app/dist:/var/lib/grafana/plugins/grafana-llmexamples-app
      - ./llmexamples-app/provisioning:/etc/grafana/provisioning

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-storage:/qdrant/storage

  # vectorapi:
  #   image: vectorapi:latest
  #   environment:
  #     PORT: 8889
  #   ports:
  #     - 8889:8889
  #   volumes:
  #     - sentence-transformers:/app/.sentence_transfomers

volumes:
  # sentence-transformers:
  qdrant-storage:
